version: "2.3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: synapsis-image
    container_name: synapsis-container-api
    ports:
      - "7070:7070"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"